### ISSUE TITLE
docker-compose exposes wrong folder for attachments

### ISSUE THREAD

**Issue by routerino** [solidnerd/docker-bookstack#108]
It looks like docker is exposing /var/www/bookstack/public/storage, where /var/www/bookstack/storage/uploads should be exposed. All attachments are getting deleted on container creation.

**Comment by AcidUK** [comment]
I don't believe this is strictly true. 

- Attachments are in /var/www/bookstack/storage/uploads
- Inline images are in /var/www/bookstack/public/uploads

You would need to mount both as volumes.

**Comment by tylwright** [comment]
Looks like #133 solves this.
