### ISSUE TITLE
0.25.0 Tag missing

### ISSUE THREAD

**Issue by markuskonojacki** [solidnerd/docker-bookstack#112]
Currently only the `latest` tag seems to have the latest version. We're missing a `0.25.0` tag.

**Comment by rancod99** [comment]
Can we fix this manually in the meantime? How?
 
Getting stuck on initial install ( ERROR: manifest for solidnerd/bookstack:0.25.0 not found)

Thanks

**Comment by markuskonojacki** [comment]
You could use `solidnerd/bookstack:latest` (which is `0.25.0` currently) in the meantime. Or if you don't like `:latest` you could do it with `solidnerd/bookstack:0.24.3`, the version before `0.25.0`.

**Comment by quanganh569** [comment]
my error same you @Derevar how we can fix that ,i need help please bro

**Comment by quanganh569** [comment]
i getting stuck

**Comment by markuskonojacki** [comment]
Like I said, in step 3 you do:
```bash
docker run -d --net bookstack_nw  \
-e DB_HOST=bookstack_db:3306 \
-e DB_DATABASE=bookstack \
-e DB_USERNAME=bookstack \
-e DB_PASSWORD=secret \
-p 8080:80 \
 solidnerd/bookstack:latest
```

You just replace the last line with either `solidnerd/bookstack:latest` or `solidnerd/bookstack:0.24.3`.

**Comment by quanganh569** [comment]
when step 1 . I'm paste "docker-compose up" on my C:\Windows\System32\cmd.exe 

then command line back answer:
C:\wamp64\www\docker-bookstack-master>docker-compose up
Pulling bookstack (solidnerd/bookstack:0.25.0)...
ERROR: manifest for solidnerd/bookstack:0.25.0 not found

**Comment by ssddanbrown** [comment]
@quanganh569 As per @Derevar's comments you'll need to modify your docker-compose file to change the image version in use.

Otherwise, Remain patient until the maintainer has time to tag the latest build.

**Comment by gerroon** [comment]
I get 

ERROR: manifest for solidnerd/bookstack:0.25.0 not found

I assume this is the issue?

**Comment by markuskonojacki** [comment]
The `0.25.1` tag is now missing as well.

**Comment by rlapleige-am** [comment]
0.25.1 is missing.

I have done a 
```
docker pull solidnerd/bookstack:latest
```

It downloaded the good tag (0.25.1)

**Comment by fam4r** [comment]
@rlapleige-am yes I can confirm that.

I edited the `docker-compose` file in the following way:

```
  bookstack:
    image: solidnerd/bookstack:latest
```

**Comment by markuskonojacki** [comment]
Unfortunately, using the `:latest` tag is not good practice. You should not use `:latest` in production environments, use a specific version instead. (for more info read this: https://container-solutions.com/docker-latest-confusion/)

**Comment by verwilst** [comment]
Please add the 0.25.* tags so we can update the Helm chart to install these versions.

**Comment by markuskonojacki** [comment]
Since we've got the `0.25.2` tag now, I'm closing this.
