### ISSUE TITLE
Bookstack doesn't start

### ISSUE THREAD

**Issue by ReinerNippes** [solidnerd/docker-bookstack#117]
Bookstack doesn't start. All I got in the logs is:

```
.....
> php artisan view:clear
Compiled views cleared!

**************************************
*     Application In Production!     *
**************************************
 Do you really wish to run this command? (yes/no) [no]:
```

**Comment by tylwright** [comment]
How are you starting the container (ex. via docker-compose or just running the image standalone)?

**Comment by ReinerNippes** [comment]
I'm writing an ansible playbook to run different container apps on one server.

https://github.com/ReinerNippes/selfhosted_on_docker/blob/master/roles/docker_bookstack/tasks/bookstack.yml

I was able to fix the problem and forgot about this issue. It works now for both images linuxserver and solidnerd.
