### ISSUE TITLE
ERROR: manifest for solidnerd/bookstack:0.25.1 not found

### ISSUE THREAD

**Issue by gandarez** [solidnerd/docker-bookstack#118]
Environment:
docker: Docker version 18.09.2, build 6247962
OS: macOS High Sierra 10.13.6

<img width="407" alt="screen shot 2019-02-19 at 11 30 07" src="https://user-images.githubusercontent.com/782854/53022347-c38ba580-3439-11e9-94a8-e323ab8852f5.png">

There's no tag `0.25.1` on Dicker Hub.

**Comment by stuartc1** [comment]
Same. Changed to :latest and it seems to work.

**Comment by pschmitt** [comment]
Duplicate of https://github.com/solidnerd/docker-bookstack/issues/112
