### ISSUE TITLE
Upgrade bookstack to 0.26.0

### ISSUE THREAD

**Issue by mehmetmuejde** [solidnerd/docker-bookstack#137]
# Beta Release v0.26.0

https://www.bookstackapp.com/blog/beta-release-v0-26-0/

**Comment by tylwright** [comment]
I have made the necessary changes and have opened PR #138.  Feel free to assign this issue to me and merge up when ready.  Thanks!

**Comment by mehmetmuejde** [comment]
Can i pull it from docker hub? Because the latest tag is 25.5.
https://hub.docker.com/r/solidnerd/bookstack/tags

**Comment by solidnerd** [comment]
I think it can be closed now `0.26.0` release is on docker hub.
