### ISSUE TITLE
messy code

### ISSUE THREAD

**Issue by jiedongd** [solidnerd/docker-bookstack#149]
when i export by PDF in Chinese，Unable to export file correctly

**Comment by solidnerd** [comment]
I think this needs more information. Could you add more information to it that could get a bigger picture ?

**Comment by jiedongd** [comment]
this was what i writed on bookstack ， but when i export one book by pdf in chinese， it become messy code，the third pic is some logs from container which image is solidnerd/bookstack:latest




------------------ 原始邮件 ------------------
发件人: "Niclas Mietz"<notifications@github.com>;
发送时间: 2019年7月6日(星期六) 下午2:13
收件人: "solidnerd/docker-bookstack"<docker-bookstack@noreply.github.com>;
抄送: "枫"<409726418@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [solidnerd/docker-bookstack] messy code (#149)




I think this needs more information. Could you add more information to it that could get a bigger picture ?

**Comment by polarathene** [comment]
@jiedongd I do not see any pictures on this thread, but [this google result might help you](https://blog.stevedong.com/post/how-to-deploy-bookstack-with-docker-compose/#how-to-fix-export-chinese-pdf-document-with-error).

It says to:
 
- Install chinese fonts onto the host system(they give an example with package manager to install some, but you could use any chinese font). 
- Then they have an environment variable for `WKHTMLTOPDF` location, and set `LANG=C.UTF-8`. 
- Finally mount the host fonts via volume bind mount: `/usr/share/fonts/truetype:/usr/share/fonts/truetype`

That should work. If that is not satisfactory, it may need additional work like fontconfig tweaks.
