### ISSUE TITLE
v0.27 removed the config folder and docker-entrypoint.sh fails to start

### ISSUE THREAD

**Issue by jcwimer** [solidnerd/docker-bookstack#161]
docker-entrypont.sh fails with sed: can't read config/app.php: No such file or directory on v0.27

**Comment by jcwimer** [comment]
See: https://github.com/BookStackApp/BookStack/commit/97fdfa6ebe3741880b958b963a6e415ee50e5a59

**Comment by jcwimer** [comment]
https://github.com/solidnerd/docker-bookstack/pull/162

**Comment by col-panic** [comment]
#165

**Comment by solidnerd** [comment]
https://github.com/solidnerd/docker-bookstack/pull/162 is merged and landed in `0.27.4-1`
