### ISSUE TITLE
Please rebuild docker image due to #162

### ISSUE THREAD

**Issue by col-panic** [solidnerd/docker-bookstack#165]
PR #162 did not find it's way into the current docker provided image, which results in the image failing with
```
Attaching to elexis-environment_bookstack_1
bookstack_1           | sed: can't read config/app.php: No such file or directory
```

**Comment by solidnerd** [comment]
We don't need to rebuild the image. Instead, you can use the latest version. It's landed in  `0.27.4-1` or latest tag if you want.
