### ISSUE TITLE
Enableing Memcached seem to stop bookstack from starting

### ISSUE THREAD

**Issue by bbenson29** [solidnerd/docker-bookstack#168]
I am trying to use Memcached with this image
I also commented out the following
`#CACHE_DRIVER=file`
`#SESSION_DRIVER=file`
and added the following 
`CACHE_DRIVER=memcached`
`SESSION_DRIVER=memcached`
`MEMCACHED_SERVERS=127.0.0.1:11211:100`

```
> php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"> php -r "!file_exists('bootstrap/cache/compiled.php') || @unlink('bootstrap/cache/compiled.php');"
Loading composer repositories with package informationInstalling dependencies (including require-dev) from lock file
Nothing to install or updateGenerating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump> @php artisan package:discover
[2019-11-25 00:09:58] production.ERROR: Class 'Memcached' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0)
: Class 'Memcached' not found at /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Cache/MemcachedConnector.php:69)"} []


                                                           
  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'Memcached' not found                              
                                                           

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```

Am not sure if I doing something wrong but when I remove the caching configurations things work perfectly fine 
Running it on AWS ECS

**Comment by patschi** [comment]
I was facing the exact same behavior when I was setting up Bookstack, unfortunately I was required to go ahead with file-based however. I'm assuming this is also related to the fact that neither memcached nor redis are installed as PHP modules in the `Dockerfile`.

But as the `.env` file is being created during container start with memcached-examples, IMHO this should be a supported setup:
https://github.com/solidnerd/docker-bookstack/blob/24653d3a8331123fd9ad01ef0830c7ed24577aa8/docker-entrypoint.sh#L31-L34

**Comment by solidnerd** [comment]
@patschi,
could you provide a short example `docker-compose.yml` with redis setup and then I'll try to fix it over the weekend.

**Comment by patschi** [comment]
Sure! Unfortunately I don't have a copy-paste-to-go config for new setups at hand, as I'm re-using my existing MySQL database:

`docker-compose.yml`
```yaml
  bookstack:
    container_name: bookstack
    image: solidnerd/bookstack:0.30.4
    env_file:
      - bookstack/bookstack.env
    volumes:
      - bookstack-uploads:/var/www/bookstack/public/uploads
      - bookstack-storage-uploads:/var/www/bookstack/storage/uploads
    ports:
      - 127.0.0.1:8088:8080
```

In `bookstack.env`: (as an example for both memcache servers)
```
CACHE_DRIVER=memcached
SESSION_DRIVER=redis
QUEUE_DRIVER=sync
MEMCACHED_SERVERS=172.20.0.1:11211:100
REDIS_SERVERS=172.20.0.1:6379:0
```
