### ISSUE TITLE
Do not run container as root

### ISSUE THREAD

**Issue by verwilst** [solidnerd/docker-bookstack#170]
Currently the container is running as root. The Helm chart on stable circumvents this by creating its own podsecuritypolicy that allows this. I would like to remove the PSP and make it use the default restricted profile.

Adding `USER 33` to the Dockerfile, making it listen on port 8080 instead of 80, and not chowning the data dirs in the entrypoint should be enough to make it work.

**Comment by solidnerd** [comment]
I will look into it on the weekend.


Bort Verwilst <notifications@github.com> schrieb am Fr. 20. Dez. 2019 um
16:51:
