### ISSUE TITLE
HTTPS and reverse proxy

### ISSUE THREAD

**Issue by phineas0fog** [solidnerd/docker-bookstack#171]
Hello all,
I use bookstack with docker behind a reverse proxy to enable HTTPS etc. So all the HTTP traffic is redirected to HTTPS but from 0.27.5 bookstack seems to had to know what is his URL :/

With the 0.24.1 version, all is OK, if I show the network calls, all are https://mydomain.tld. But now I want to use v0.27.5, the app.js file is in HTTP. So can I specify the URL of the instance with env var or anything else ?

Thanks

**Comment by azN2** [comment]
Hello,

Have you tried APP_URL=https://domain.tld as an environment variable?
I had a similar problem and this fixed it.
