### ISSUE TITLE
Docker keeps restarting?

### ISSUE THREAD

**Issue by ghost** [solidnerd/docker-bookstack#172]
Sorry, somehow I posted?

Anyways, the docker keeps restarting, I pulled it with solidnerd/bookstack.

This is how I created it:

docker create
--restart=always
--name=bookstack
--link mariadb-bookstack:mariadb-bookstack
-e DB_HOST=mariadb-bookstack:3306
-e DB_DATABASE=bookstack
-e DB_USERNAME=bookstack
-e DB_PASSWORD=pass
-p 8011:80
solidnerd/bookstack

Any help would be great, thank you!

EDIT: Also I am very new at using docker, so please bare with me.

**Comment by TheeKuZu** [comment]
Sorry, somehow I posted?

Anyways, the docker keeps restarting, I pulled it with solidnerd/bookstack.

This is how I created it:

docker create \
  --restart=always \
  --name=bookstack \
  --link mariadb-bookstack:mariadb-bookstack \
-e DB_HOST=mariadb-bookstack:3306 \
-e DB_DATABASE=bookstack \
-e DB_USERNAME=bookstack \
-e DB_PASSWORD=pass  \
-p 8011:80 \
solidnerd/bookstack

Any help would be great, thank you!

**Comment by samuellima06** [comment]
> Sorry, somehow I posted?
> 
> Anyways, the docker keeps restarting, I pulled it with solidnerd/bookstack.
> 
> This is how I created it:
> 
> docker create
> --restart=always
> --name=bookstack
> --link mariadb-bookstack:mariadb-bookstack
> -e DB_HOST=mariadb-bookstack:3306
> -e DB_DATABASE=bookstack
> -e DB_USERNAME=bookstack
> -e DB_PASSWORD=pass
> -p 8011:80
> solidnerd/bookstack
> 
> Any help would be great, thank you!
> 
> EDIT: Also I am very new at using docker, so please bare with me.

Did you solve it?
