### ISSUE TITLE
Please provide v0.28.0 docker image

### ISSUE THREAD

**Issue by col-panic** [solidnerd/docker-bookstack#173]
Please provide an updated docker image

**Comment by kmplngj** [comment]
Did anyone tried to move to linuxserver/bookstack? Does the work without problems?

**Comment by GeorgeHahn** [comment]
I migrated from `solidnerd/bookstack:0.27.5` to `linuxserver/bookstack:v0.28.2-ls81`

1. Change environment variables: `DB_USERNAME -> DB_USER`, `DB_PASSWORD -> DB_PASS`, add `PUID`, `PGID`
2. Drop port from `DB_HOST`
3. The LSIO container uses different volumes (see their docs for this)
4. Manually moved files from this container's `/uploads` to LSIO's `/config/www/uploads`
5. The LSIO container will generate a new appkey

This container doesn't document its `APP_KEY` environment variable, so most people probably use the default value. That's bad. You can set `/config/BOOKSTACK_APP_KEY.txt` to `SomeRandomStringWith32Characters` to get things working, but you'll want to generate a real key after migrating to the LSIO container. This will reset user passwords.
