### ISSUE TITLE
Apache Port changed from 80 to 8080 in container in recent update

### ISSUE THREAD

**Issue by AcidUK** [solidnerd/docker-bookstack#186]
Sometime recently (in the last week or so?) I became unable to access this container. Further investigation reveals that the apache instance in the container is now serving on port 8080.

```console
root@7d0ad393d576:~# cat /etc/apache2/sites-enabled/000-default.conf
<VirtualHost *:8080>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        ServerName bookstack

        DocumentRoot /var/www/bookstack/public

        <Directory "/var/www/bookstack/">
            Options FollowSymLinks MultiViews
            AllowOverride All
            Require all granted
        </Directory>
        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        LogLevel info
</VirtualHost>
```

From the readme for this project it still looks like you're mapping 8080 on the host to 80 on the container.

The fix for me was to update my docker-compose file to point my reverse proxy (traefik) at port 8080 in the container, but if I'm right and this has changed for everyone that might mean a lot of different solutions for different people. 

If this is confirmed, I'm not sure if it would be better to change the port back?

**Comment by AcidUK** [comment]
I can see this was intentional due to running apache as non root (meaning it can no longer bind to ports < 1024).

See 6763e15

Would it be worth 
1) Having a big notice on the README to save others time in the upcoming weeks?
2) Amending the README examples which still map port 8080 on the host to 80 on the container

**Comment by ruben-rodriguez** [comment]
Hello @AcidUK !

Just adding that for me it was not enough to use traefik.port and had to point it using traefik.http.services.<service_name>.loadbalancer.server.port as the container seems to be exposing both 80 and 8080 ports (even if in the docker-compose I'm only exposing 8080...)
