### ISSUE TITLE
Cannot access to mapped port container

### ISSUE THREAD

**Issue by gotchai** [solidnerd/docker-bookstack#202]
After following the documentation on dockerhub : I change the mapped port 
1.Create a shared network:

docker network create bookstack_nw

2.MySQL container :

docker run -d --net bookstack_nw  \
-e MYSQL_ROOT_PASSWORD=secret \
-e MYSQL_DATABASE=bookstack \
-e MYSQL_USER=bookstack \
-e MYSQL_PASSWORD=secret \
 --name="bookstack_db" \
 mysql:5.7.21

3.Create BookStack Container

docker run -d --net bookstack_nw  \
-e DB_HOST=bookstack_db:3306 \
-e DB_DATABASE=bookstack \
-e DB_USERNAME=bookstack \
-e DB_PASSWORD=secret \
**-p 9999:8080 \**
 solidnerd/bookstack:0.27.4-1

Then the port is not correctly working on 9999 for this example, I cannot access to bookstack. Nevertheless I can access it inside the container on port 8080

**Comment by solidnerd** [comment]
Hey @stx233,
I think you need to update you image to at least `solidnerd/bookstack:0.29.0` before this release the port `80/tcp` was used for access the container. If this doesn't work for you let me know.

**Comment by gotchai** [comment]
Great ! Sorry I did not set latest on solidnerd/latest
Thank you
