### ISSUE TITLE
HTTPS Requests

### ISSUE THREAD

**Issue by tarkin2020** [solidnerd/docker-bookstack#203]
hello,

how I can get https requests get to work? it seems like the container only accepts http requests....

regards

**Comment by NaeiKinDus** [comment]
Tried what is suggested in #171 ?

**Comment by peterspat** [comment]
> 
> 
> Tried what is suggested in #171 ?

Thank you very much. #171 worked for me  :-)

**Comment by solidnerd** [comment]
Does it need an improvement for the docs ? 

How to configure the reverse proxy for the container. Feel free to create one.

**Comment by tarkin2020** [comment]
Worked also for me! Yes please improve the docs.


Niclas Mietz <notifications@github.com> schrieb am Sa. 20. Juni 2020 um
20:34:
