### ISSUE TITLE
container start fails if DB_PASSWORD is changed from secret to something else

### ISSUE THREAD

**Issue by johannes-gilbert** [solidnerd/docker-bookstack#207]
When changing the database password used in the [docker-compose.yml](https://github.com/solidnerd/docker-bookstack/blob/ff5b2ec0ad320c04f8029d06e642c25e3ac61f48/docker-compose.yml) (lines 6, 9, 21) the container won't start up (only the mysql container starts). Looking into the logs for the bookstack container shows the following error:

```
Starting Migration...
 
   Illuminate\Database\QueryException  : SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'172.21.0.3' (using password: YES) (SQL: select * from information_schema.tables where table_schema = bookstack and table_name = migrations and table_type = 'BASE TABLE')
 
  at /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|
 
  Exception trace:
 
  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'172.21.0.3' (using password: YES)")
      /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31
 
  2   PDOException::("SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'172.21.0.3' (using password: YES)")
      /var/www/bookstack/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27
```

When changing the ```MYSQL_ROOT_PASSWORD``` (line 6), ```MYSQL_PASSWORD``` (line 9) and ```DB_PASSWORD``` (line 21) back to ```secret``` everything works fine again. However, I would like to change the default password for obvious reasons. Did I miss anything to be done in advance to changing this password?

BTW: i'm starting the containers using ```docker-compose up -d```

**Comment by ptoulouse** [comment]
When you launched docker-compose the first time, you created a new database naked bookstack with a user and root passwords "secret". If you then change the passwords in the docker-compose file, it is too late, the database is already created and you need the "secret" password to access it.

Assuming you have not put any content in bookstack, here is how to fix this:
- Delete the database folder and its content.
- Put the desired password in docker-compose.yml.
- Relaunch using docker-compose.

**Comment by johannes-gilbert** [comment]
> When you launched docker-compose the first time, you created a new database naked bookstack with a user and root passwords "secret". If you then change the passwords in the docker-compose file, it is too late, the database is already created and you need the "secret" password to access it.
> 
> Assuming you have not put any content in bookstack, here is how to fix this:
> 
> * Delete the database folder and its content.
> * Put the desired password in docker-compose.yml.
> * Relaunch using docker-compose.

Thanks for your answer and proposal. I deleted the database folder and its content from ```/var/lib/mysql/```. I also removed any related docker container via ```docker rm```. Still I get the same issue when launching via ```docker-compose up -d```. The error is exactly the same like mentioned above.

Did I miss deleting anything else? Is it sufficient to delete the related folder under ```/var/lib/mysql/```?

**Comment by solidnerd** [comment]
Hey @johannes-gilbert, 
for a secure delete use `docker-compose down -v`. This will also delete all volumes. I think this could solve your problem.

**Comment by johannes-gilbert** [comment]
> Hey @johannes-gilbert,
> for a secure delete use `docker-compose down -v`. This will also delete all volumes. I think this could solve your problem.

Thanks. I just was on my way to describe that deleting the corresponding volume is necessary. Looking into the [docker-compose.yml](https://github.com/solidnerd/docker-bookstack/blob/ff5b2ec0ad320c04f8029d06e642c25e3ac61f48/docker-compose.yml) shows that no host-mounted volume is used but a named volume. 

Hence I looked up all bookstack related volumes via ```docker volume ls```. There are three volumes which I deleted by using ```docker volume rm <name>```. That solved my issue.

Thanks for the quick support and help!

**Comment by s-gbz** [comment]
I faced the same problem. Strangely enough `docker volume prune` didn't work out.
However, the following snippet removed the volumes thanks to [this SO reply](https://stackoverflow.com/a/52326805/11515036)!

```
docker-compose down --volumes
```
