### ISSUE TITLE
Container does not remember settings and data, upon restarting docker

### ISSUE THREAD

**Issue by neelduttahere** [solidnerd/docker-bookstack#210]
Hey I am new to docker, and I having this issue where, when I restart the docker application in windows (right click on notification bar icon and restart), the containers do not remember my bookstack settings and data, hence it resets itself. Please let me know what can be done, or whether this is a bug.

**Comment by morganpartee** [comment]
@neelduttahere You just need to map volumes for the data to persist. Scroll down on the main repo readme and there's an example. By default docker doesn't persist any data- You have to tell it where to store directories on your local machine.

**Comment by neelduttahere** [comment]
Thank you for the information!
