### ISSUE TITLE
problem with the port

### ISSUE THREAD

**Issue by Shadikho** [solidnerd/docker-bookstack#211]
Hello,
I have been using your image for near a year now. Everything was fine until some time ago. I was using version 0.27.5
I realized that the url doesn't work anymore (I got an error everytime I tried to connect) so I updated it to the newer version. The problem is the new version without me specifying it listens on the port 8080. Now this provides an issue since I need it to listen on port 80 and map it to another port using nginx. 8080 is my apache port and I don't want the requests to be handle by apache. 
what should I do?
Thank you in advance
Regards

**Comment by karillon** [comment]
Hello,
I have the same problem. 
Did you find a solution?
Thanks

**Comment by Shadikho** [comment]
> Hello,
> I have the same problem.
> Did you find a solution?
> Thanks

Hi @karillon ,
unfortunately not. I just used the last image where this was not an issue with it. I think version 0.27.5 is the last one that works with port 80.

**Comment by karillon** [comment]
It seems that it is a compatibility issue between last mariaDB ans PHP 7.2.
https://stackoverflow.com/questions/64677836/sqlstatehy000-general-error-1835-malformed-communication-packet-on-laravel
On app logs, I see that the app don't connect to the DB.
I have been using the image for near a year now too

**Comment by Shadikho** [comment]
> It seems that it is a compatibility issue between last mariaDB ans PHP 7.2.
> https://stackoverflow.com/questions/64677836/sqlstatehy000-general-error-1835-malformed-communication-packet-on-laravel
> On app logs, I see that the app don't connect to the DB.
> I have been using the image for near a year now too

Have you tried it?
I eventually did a new installation of both bookstack and mysql. Just backed up my old database and import it to the new one and now it works!! I tried all other solutions on the Internet but no luck (at least for me).

**Comment by Rinma** [comment]
There is no problem between MariaDB and PHP. With version [0.28.0](https://github.com/solidnerd/docker-bookstack#changes) the port was changed from 80 to 8080, also the way the database connection is defined changed, which could cause the other issue. Can't you just point your Nginx reverse proxy to the new port? If not why not change the port with the docker command `docker run -p 80:8080 ...` or compose file?

**Comment by Shadikho** [comment]
> There is no problem between MariaDB and PHP. With version [0.28.0](https://github.com/solidnerd/docker-bookstack#changes) the port was changed from 80 to 8080, also the way the database connection is defined changed, which could cause the other issue. Can't you just point your Nginx reverse proxy to the new port? If not why not change the port with the docker command `docker run -p 80:8080 ...` or compose file?

Hi Rinma,
to answer your question, no i can't do either. My Nginx not only supports bookstack, but many other applications and for that I have to change everything in my server (simply not worth to risk screwing everything). Also as I said before port 8080 is used already and I can't change that. So, changing the port in bookstack docker compose file will not work. I just don't understand why the port should have changed in the new version! It makes it quiet complicated in my case to upgrade it (so far no upgrade plan).
