### ISSUE TITLE
Docker / Synology: Uploads not working: path not writeable

### ISSUE THREAD

**Issue by RicardoMusch** [solidnerd/docker-bookstack#220]
At first, thanks for this docker image and all the work that goes into it! :)

After getting it to run on my Docker which runs on Synology I seem to be having issues getting file uploads working.

`File path /uploads/images/cover_book/2021-01/photo.jpg could not be uploaded to. Ensure it is writable to the server.`

I have mapped both storage and public uploads folders to a docker accessible bookstack subfolder.
Or should they both go to the same local folder?

**Comment by RicardoMusch** [comment]
Should anyone on a Synology get this same issue. The solution was to give the SYSTEM user explicit admin permissions to the mounted folder.

I am unsure why that would not happen automatically but this was the solution!

**Comment by HeavenlyEntity** [comment]
> Should anyone on a Synology get this same issue. The solution was to give the SYSTEM user explicit admin permissions to the mounted folder.
> 
> I am unsure why that would not happen automatically but this was the solution!

@RicardoMusch Could you elaborate what that looks like? I am using AWS ECS to host. What do I have to do to get it to work?
