### ISSUE TITLE
wkhtmltopdf generating wrong TOC links

### ISSUE THREAD

**Issue by maggie44** [solidnerd/docker-bookstack#226]
## Expected Behavior
Links should point to the heading for that section as can be seen when done through the BookStack development environment. 

## Current Behavior
When exporting a page to pdf with wkhtmltopdf and opening it, clicking one of the TOC links, it doesn't take me to the correct location and shows a meaningless link address, like file:///tmp/knp_snappy5ff65ed5491ae7.13561238.html.

This behaviour cannot be reproduced on the official BookStack install or development environment, only the Linuxserver and Solidnerd image. 

## Steps to Reproduce

Create a page with some headers
Configure BookStack to use wkhtmltopdf for pdf-generating
Export and open
Click one of the TOC links

Process of elimination has narrowed this down to the version of wkhtmltopdf running:

Development environment: `wkhtmltopdf 0.12.6 (with patched qt)`
Linuxserver: `wkhtmltopdf 0.12.5`
Solidnerd: `wkhtmltopdf 0.12.5`

So I updated the Linuxserver image to the 0.12.6 (actually I bumped the Alpine container version to .13, which then pointed it to the new repository which had the 0.12.6 in it). But the issue still occurred.

Then I pulled the latest build directly from the website (https://wkhtmltopdf.org/downloads.html) into the Solidnerd container, and the issue was resolved.

The difference, is in 1. the wkhtmltopdf version became: `wkhtmltopdf 0.12.6`. In scenario 2. the version became: `wkhtmltopdf 0.12.6 (with patched qt)`

The solution then it appears, is to install wkhtmltopdf 0.12.6 (with patched qt. More can be read about qt here: https://wkhtmltopdf.org/downloads.html).

This should be relatively easy for the Solidnerd container as it can be pulled directly from the source (https://wkhtmltopdf.org/downloads.html). Will need to account for different architectures though. 

https://github.com/BookStackApp/BookStack/issues/2459#issuecomment-766504299

**Comment by maggie44** [comment]
A combination of wkhtmltopdf not updating all their releases at the same time under the 'latest' tag in their repo and their own naming conventions for architectures in the files means more is required than ideal for keeping this easy to maintain. 

For user ease, something like this, manually bumping the version, but would need to replace {} with a script to deduce the correct arch. uname -m won't return the same format as that used in the naming of the releases. 
```
ARG VERSION="0.12.6-1"

https://github.com/wkhtmltopdf/packaging/releases/download/$VERSION/wkhtmltox_$VERSION.buster_ {}.deb
```

Then a line to install the deb package of course. But this would be more work to maintain here in the repo, especially if the naming conventions change in wkhtmltopdf repo. 

Alternatively, could remove the install of wkhtmltopdf from the Dockerfile, and put something in the entry script that checks for the .deb file in the mounted folder and if present installs it. That way a user would manually download the appropriate version as per the BookStack documentation and drop it in. Some advantages to this, one less install in containers where people aren't using wkhtmltopdf for example.

**Comment by solidnerd** [comment]
Hey @maggie0002,
since you are more into the topic. I would really like to see a PR from your side with the best solution. I would see more it more during a Docker Build step. I would be also fine for me to have it in a script and install it.
