### ISSUE TITLE
Mysql backup

### ISSUE THREAD

**Issue by shyamjos** [solidnerd/docker-bookstack#24]
Hi , I am bit worried about data loss , Which is best way to backup docker instance (including mysql dump, site  configuration,images)

**Comment by deluxejuice** [comment]
Have you checked [this](https://www.bookstackapp.com/docs/admin/backup-restore/). You can access mysql with `docker exec -it mysql /bin/bash`

**Comment by amchelmer** [comment]
I'm running the mysql volume in a host directory instead of docker volume. This way you can backup using a cronjob. To do this, remove `mysql-data`from `volumes` and replace `mysql-data:/var/lib/mysql ` with `/absolute/path/to/folder:/var/lib/mysql`
