### ISSUE TITLE
Track new versioning

### ISSUE THREAD

**Issue by smacz42** [solidnerd/docker-bookstack#260]
Per https://www.bookstackapp.com/blog/bookstack-release-v21-04/

> In terms of version numbers, we’re jumping from Beta v0.31 to BookStack v21.04. As mentioned above, I couldn’t really define a v1.0 so we’re skipping right over it and using the Ubuntu versioning system as inspiration. BookStack versions will now be in the format of v<2 DIGIT YEAR>.<2 DIGIT MONTH>[.<OPTIONAL PATCH DIGIT>]. As an example:
>
> _v21.06 (June 2021 launched feature release)_
> _v21.06.5 (Fifth patch of June 2021 release, even if released in a later month)_
> _v22.10 (October 2022 launched feature release)_
>
> That change is technically compatible with the old versioning, while now providing context about the release date within the version. This can be extremely useful when people reference their BookStack version as it’ll instantly provide context of release date without needing to look that up.

There are currently several releases for 21.04 and 21.05, with the latest being 21.05.3. (See here: https://github.com/BookStackApp/BookStack/releases)

**Comment by solidnerd** [comment]
Hey @smacz42, 
thanks for reaching out. I seems there is no technical difference to the old scheme.

What currently missing here is a Bot to update automatically the docker image when a new release happens. 

I think this can be released with a [renovate bot ](https://github.com/marketplace/renovate).

**Comment by smacz42** [comment]
Just so the bot is happy, I just wanted to comment that the bot discussed above has not been implemented, nor have the releases been able to be dockerized. No rush, but I didn't want this to close.
