### ISSUE TITLE
When mounting a theme folder, /var/www/html is deleted in the container (except for the theme folder)

### ISSUE THREAD

**Issue by bensulli** [SolidNerd/docker-bookstack#273]
Hi,

When I add this volume mount:
      - ./themes/themename:/var/www/html/themes/themename

Where "themename" contains lang/en/*.php

Once the container starts, the entire /var/www/html is empty _except_ for the themes folder.

Probably just doing something dumb in docker, but if someone could point me to a working docker-compose that leverages the bookstack theme system, I'd appreciate it!

**Comment by ssddanbrown** [comment]
Hi @bensulli,

Looking at the way this container is built, BookStack appears to be installed in the container at `/var/www/bookstack`. 
So you could try instead mounting to `/var/www/bookstack/themes/themename` and see if that works.
Just to confirm though, have not tried this myself.
