### ISSUE TITLE
Quickstart doesn't mention the need to edit APP_URL in docker-compose.yml

### ISSUE THREAD

**Issue by andybak** [SolidNerd/docker-bookstack#294]
This confused me for a bit. localhost:8080 redirects to example.org unless you edit APP_URL.

It would be useful to mention this in the Quickstart section of the readme.

**Comment by solidnerd** [comment]
> The APP_URL parameter should be the base URL for your BookStack instance without a trailing slash. For example: APP_URL=http://example.com

Is already in the readme. Can be probably moved to a better view. Feel free to do it :)

**Comment by ddibiasi** [comment]
If anyone else is struggling with setting up a quick instance of BookStack due to this issue:
1. Edit docker-compose.yml
2. Set APP_URL to nothing (eg.: "APP_URL=")
3. docker-compose up
