### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by Peter1994** [SolidNerd/docker-bookstack#296]
Hello,

Is it possible to implement HTTPS support into this image?

By default it should listen on HTTPS with a self-signed certificate.

Thanks in advance.

**Comment by ssddanbrown** [comment]
@Peter1994 From what I've seen of docker setups, It's most common to run your own reverse proxy in front of a container such as this to handle routing and HTTPS.

**Comment by Peter1994** [comment]
@ssddanbrown I was worried you were going to suggest that. SSL proxy it be. Thanks anyways.

**Comment by ssddanbrown** [comment]
@Peter1994 If it helps I've found nginx proxy manager quite nice to use:
https://nginxproxymanager.com/

I [use it in this video](https://www.youtube.com/watch?v=dbDzPIv8Cf8). That guide uses a different BookStack container but the general process would be the same.

**Comment by Peter1994** [comment]
@ssddanbrown Thanks for the suggestion. I've already deployed a Traefik container for the Bookstack instance.
