### ISSUE TITLE
Version bump not reflected in YAML

### ISSUE THREAD

**Issue by almereyda** [SolidNerd/docker-bookstack#3]
The YAML example still looks for an image tagged for version `0.10` as of

https://github.com/SolidNerd/docker-bookstack/blob/master/docker-compose.yml#L4

**Comment by SolidNerd** [comment]
Thanks for the hint. Feel free to create a Pull Request for that.  Or I will fix this when I have a computer in my near.

**Comment by almereyda** [comment]
My local development machine is currently affected by a bug concerning
Fedora 24, SELinux and Docker, why I cannot build the image with the
desired tag. I can issue a PR from within GitHub's web interface, but I
couldn't validate it's working then.

**Comment by SolidNerd** [comment]
It's fixed with PR #4  . So I will close this now and if you have any other problems open a new issue for that. Thanks for your issue.
