### ISSUE TITLE
Ability to set `STORAGE_S3_ENDPOINT`

### ISSUE THREAD

**Issue by rjhenry** [SolidNerd/docker-bookstack#309]
As documented in the upstream ([here](https://www.bookstackapp.com/docs/admin/upload-config/)), the `STORAGE_S3_ENDPOINT` needs to be customised if using non-Amazon S3-compatible services. I'd like to be using my self-hosted MinIO instance  to avoid needing to manage persistence for this instance.

Templating that in directly could be awkward, assuming that no `STORAGE_S3_ENDPOINT` line should end up in `.env` if this option isn't needed; the cleanest way I can think of to do this is something along the lines of:
```bash
      if [ -n ${STORAGE_S3_ENDPOINT} ]; then
        echo "      STORAGE_S3_ENDPOINT=${STORAGE_S3_BUCKET}" >> ".env"
      fi
```
in the entrypoint.sh, around the line 81/82 mark.

**Comment by ssddanbrown** [comment]
@rjhenry I think you should be able to just define a `STORAGE_S3_ENDPOINT` environment variable on the bookstack container to use that option if needed, unless I've misunderstood and you're attempting something specific here?

**Comment by rjhenry** [comment]
Doesn't seem to work in that manner in my testing:
```shell
$ k exec -it -n bookstack bookstack-bf6c4b54b-x9pgk -- env | grep ENDPOINT
STORAGE_S3_ENDPOINT=https://minio.mydomain.tld
```
and yet attempted uploads simply fail, with the following in the container logs, and nothing in the MinIO trace - Bookstack doesn't actually reach out to my MinIO host at all.
```
bookstack:80 10.42.0.89 - - [22/Mar/2022:15:24:13 +0000] "POST /images/gallery?uploaded_to=1 HTTP/1.1" 500 1491 "https://bookstack.mydomain.tld/books/demo/page/test/edit" "Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0"
```
The console in my browser simply shows a 500 Internal Server Error for the upload.

I did check that it wasn't a more generic issue with uploading to S3 in the first place by creating a quick "Real S3" bucket to test, and that worked fine.

**Comment by ssddanbrown** [comment]
@rjhenry Might be worth catting out the contents of the BookStack log file at `/var/www/bookstack/storage/logs/laravel.log` from within the container if possible, since that's where any error logs from BookStack should be but not sure if they're exposed by default with this container.

**Comment by rjhenry** [comment]
Thanks @ssddanbrown - I had the same thought. Looks like it was complaining about a missing `STORAGE_S3_REGION` value that I didn't see. I'll contribute to the upstream doc saying it's a needed value, and close off this issue. Thanks for the help (and the amazing project)!

Edit: For those interested, the PR to add to the doc is here: https://github.com/BookStackApp/website/pull/115
