### ISSUE TITLE
Looking for active Maintainers

### ISSUE THREAD

**Issue by solidnerd** [SolidNerd/docker-bookstack#319]
Since most of you aware that this repository ist mostly not active maintained and pull requests are open for a long. 

Mostly my own target has changed over the time and I want still that other people can use it. So for that I'm looking for maintainers that want to contribute.

**Comment by rjhenry** [comment]
I don't know how great a job I'd be able to do, but I'm happy to start reviewing some pull requests and so on - mostly things like version updates and the like. That said, the container build file doesn't look too complex, so I expect I can assist with that, too.

**Comment by mr-vinn** [comment]
I would also be willing to be a maintainer.  I run work and personal BookStack instances with this image, so I would love to see it maintained and would be happy to help make that happen.

**Comment by csongs** [comment]
I can also help to maintain.
I don't use linuxserver/bookstack because it doesn't support rootless.
