### ISSUE TITLE
container appears to be waiting for some kind of user input

### ISSUE THREAD

**Issue by tupcakes** [solidnerd/docker-bookstack#35]
I'm trying to get bookstack setup in docker using an external mariaDB instance on another server. However when the container starts the logs seem to indicate that it's waiting for some kind of input and the application never comes up. I've got the following environment variables setup.

DB_HOST
DB_DATABASE
DB_USERNAME
DB_PASSWORD

I'm sure I'm missing something...

5/12/2017 11:07:59 AM Do you really wish to run this command? (yes/no) [no]:
5/12/2017 11:17:04 AM > 2017-05-12T16:17:43.511073944Z wait-for-db: waiting for db.domain.net:3306
5/12/2017 11:17:44 AMwait-for-db: done
5/12/2017 11:17:44 AMDo not run Composer as root/super user! See https://getcomposer.org/root for details
5/12/2017 11:17:44 AM> php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"
5/12/2017 11:17:44 AM> php -r "!file_exists('bootstrap/cache/compiled.php') || @unlink('bootstrap/cache/compiled.php');"
5/12/2017 11:17:44 AMLoading composer repositories with package information
5/12/2017 11:17:44 AMInstalling dependencies (including require-dev) from lock file
5/12/2017 11:17:44 AMNothing to install or update
5/12/2017 11:17:44 AMGenerating autoload files
5/12/2017 11:17:44 AM> Illuminate\Foundation\ComposerScripts::postInstall
5/12/2017 11:17:44 AM> php artisan optimize
5/12/2017 11:17:44 AMGenerating optimized class loader
5/12/2017 11:17:45 AMThe compiled services file has been removed.
5/12/2017 11:17:45 AM> php artisan cache:clear
5/12/2017 11:17:45 AMCache cleared successfully.
5/12/2017 11:17:45 AM> php artisan view:clear
5/12/2017 11:17:46 AMCompiled views cleared!
5/12/2017 11:17:46 AM**************************************
5/12/2017 11:17:46 AM*     Application In Production!     *
5/12/2017 11:17:46 AM**************************************
5/12/2017 11:17:46 AM
5/12/2017 11:17:46 AM Do you really wish to run this command? (yes/no) [no]:

**Comment by tupcakes** [comment]
ok I think I figured it out. I'm running docker with rancher and was able to get the container to bypass the yes/no question by changing the console to none. Rancher defaults to interactive & TTY.

**Comment by fklingler** [comment]
This is still a real problem. I'm using the Docker app in my Synology NAS and I can't deactivate the console.

The line `php artisan key:generate` shouldn't be here in the startup file. The AppKey should be generated when you first launch the laravel app. I will test this in local and write a PR for the repository if the test is conclusive.
