### ISSUE TITLE
Version v23.01 is out

### ISSUE THREAD

**Issue by mariushosting** [SolidNerd/docker-bookstack#378]
Please update the container image from version 22.11.1 to 23.01

**Comment by ssddanbrown** [comment]
Pretty sure the team are already on it (#377) (86e6c339ca1655a8c9c53164b91eecf3f3e3d6f7).

**Comment by mariushosting** [comment]
> Pretty sure the team are already on it (#377) ([86e6c33](https://github.com/solidnerd/docker-bookstack/commit/86e6c339ca1655a8c9c53164b91eecf3f3e3d6f7)).

Thank you Dan! didn't see it!
