### ISSUE TITLE
Missing permissions when running with rootless podman

### ISSUE THREAD

**Issue by stebit** [SolidNerd/docker-bookstack#379]
When running the container in a rootless podman environment, uploading photos and documents is not possible, as the permissions on `/var/www` aren't set properly. Bookstack gives the output `File path /uploads/images/gallery/2023-02/pic.png could not be uploaded to. Ensure it is writable to the server.'`

Other projects solve this by `chown`ing the directories (i.e. [Syncthing](https://github.com/syncthing/syncthing/blob/99595ce3d9b593cb71cb9895529031f80b9d0fe5/script/docker-entrypoint.sh#L17)).

I just tried to add a similar `chown` command to the `docker-entypoint.sh` (`chown -R www-data:www-data /var/www/bookstack`), but this just ends in `chown: changing ownership of '/var/www/bookstack/public/uploads': Operation not permitted` and the container stopping.

Has anyone figured out how to modify the image to make it work? I have hardly any experience with Dockerfiles and would appreciate any kind of hints.

**Comment by stebit** [comment]
Ah, a simple `podman unshare chown` will do too. Changing anything about the image seems to be unnecessary.

**Comment by tim-elmer** [comment]
> Ah, a simple `podman unshare chown` will do too. Changing anything about the image seems to be unnecessary.

To clarify (since it took me a couple of tries to figure out what I needed to do):
```shell
podman unshare chown -R www-data:www-data /path/to/volume/on/host

# Or if the www-data user/group doesn't exist:
podman unshare chown -R 33:33 /path/to/volume/on/host
```

This should probably be documented somewhere other than an issue.

**Comment by rjhenry** [comment]
> This should probably be documented somewhere other than an issue.

This project is explicitly for Docker, but I'd welcome a PR to add some documentation.
