### ISSUE TITLE
Unable to download file after upload

### ISSUE THREAD

**Issue by CloudStrifer** [SolidNerd/docker-bookstack#390]
Hello, I have a problem now.
I installed it by running docker-compose up -d . After successful access, I uploaded a  file, but I couldn't download it. Its url is:
http://x.x.x.x:8080/attachments/18
![QQ截图20230414115716](https://user-images.githubusercontent.com/15940209/231938327-728e7769-76e6-4b2c-b171-5cfefa4c5e18.png)
The prompt says,
The page at http://x.x.x.x:8080/attachments/18 may be temporarily down, or it may have moved permanently to a new URL.

My config file is docker-compose.yml

        version: '2'
        services:
           mysql:
             image: mysql:8.0
             environment:
             -MYSQL_ROOT_PASSWORD=secret
             -MYSQL_DATABASE=bookstack
             -MYSQL_USER=bookstack
             -MYSQL_PASSWORD=secret
             volumes:
             - mysql-data:/var/lib/mysql
             privileged: true
        
           bookstack:
             image: solidnerd/bookstack:22.04
             depends_on:
             -mysql
             environment:
             -DB_HOST=mysql:3306
             -DB_DATABASE=bookstack
             -DB_USERNAME=bookstack
             -DB_PASSWORD=secret
             #set the APP_ to the URL of bookstack without without a trailing slash APP_URL=https://example.com
             - APP_URL=http://x.x.x.x:8080
             volumes:
             - uploads: /var/www/bookstack/public/uploads
             - storage-uploads: /var/www/bookstack/storage/uploads
             ports:
             - "8080:8080"
        
        volumes:
          mysql-data:
          uploads:
          storage-uploads:

Can you help me find out why?

**Comment by rjhenry** [comment]
I've just tried this with the same settings and had no such issue. Would it be possible to get some logs from you to see what's going on? You may need to enable debugging (see [here](https://www.bookstackapp.com/docs/admin/debugging/)) to do so!

**Comment by CloudStrifer** [comment]
Thank you very much, I just tried it and changed the version to 22.03.1, and it can be downloaded normally, so it may be a version problem, right? I haven’t paid attention to the log, but it can be used anyway, thank you very much
