### ISSUE TITLE
Remove in-container `.env` file in favour of container runtime environment settings

### ISSUE THREAD

**Issue by rjhenry** [SolidNerd/docker-bookstack#408]
As noted in [this comment](https://github.com/solidnerd/docker-bookstack/issues/388#issuecomment-1493552968) and again [here](https://github.com/solidnerd/docker-bookstack/issues/406#issuecomment-1617620367), setting values in the in-container `.env` file has caused and is likely to cause additional headaches.

Remove the part of the entrypoint script that sets up the `.env` file and provide documentation on how to migrate if needed.

**Comment by rjhenry** [comment]
This is being addressed in #409.

**Comment by stavros-k** [comment]
This can be closed now I guess!
Thanks for the work!
Going to try this tomorrow!
