### ISSUE TITLE
`latest` tagged image is not the latest image

### ISSUE THREAD

**Issue by ssddanbrown** [SolidNerd/docker-bookstack#410]
Sorry if this is a known part of your own process, but I noticed that `latest` is currently pointing to the `23.6` version of the image whereas users might expect this to point to `23.6.0-1`. 
Just raising after getting confused helping a user deal with the SAML config issue you fixed yesterday, while having their container updated to use the `latest` image.

If it's a real edge-case pain to tag your own patched updates with `latest`, then I respect that and am planning a BookStack patch release in the next day or two which I'd assume would help get things aligned again anyway.

**Comment by rjhenry** [comment]
Thanks for pointing it out @ssddanbrown - I hadn't noticed (as I use tagged releases only) and hadn't looked too closely at the Actions workflow that updates the `latest` tag. Without digging in too deeply, I suspect it's an artifact of using SemVer's pre-release indicator to manage the build-of-the-Docker-project.
I'll look into whether there's a better way of managing releases and/or version numbers later.

**Comment by sebzan** [comment]
@rjhenry: Hope you guys take care of this small matter quickly so it will work smooth again for us portainer users (who are not so hardcore in linux/docker). :)

**Comment by rjhenry** [comment]
I've tweaked the workflow to auto-tag `latest` on all release builds. It's not perfect, but as long as Bookstack is being developed and changes aren't being backported I can see no glaring issues.

**Comment by ssddanbrown** [comment]
Thanks again for your fast efforts @rjhenry!

> but as long as Bookstack is being developed and changes aren't being backported I can see no glaring issues

Yeah, I have no plans on supporting multiple streams of BookStack. The slowly evolving single linear upgrade path has worked well so far and I have no reason to change.
If that was to change I'd probably provide notice to downstream projects anyway.
