### ISSUE TITLE
Restore database with sql file

### ISSUE THREAD

**Issue by AlexsanderCostaDEV** [SolidNerd/docker-bookstack#420]
I have a .sql file and I would like to restore this file to the docker-bookstack database. How can I do this please.
![sql](https://github.com/solidnerd/docker-bookstack/assets/57103682/553fff6a-f280-420c-b5f8-57485c31a128)

**Comment by rjhenry** [comment]
Assuming you're using the standard `docker compose up` deployment:
`docker exec -i  docker-bookstack-mysql-1 mysql -ubookstack -psecret bookstack < 127_0_0_1.sql`

For more information, read the [MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/backup-and-recovery.html) and the [Docker documentation](https://docs.docker.com/engine/reference/commandline/exec/).
