### ISSUE TITLE
Offer a way to update php.ini at startup based on `FILE_UPLOAD_SIZE_LIMIT`

### ISSUE THREAD

**Issue by stavros-k** [SolidNerd/docker-bookstack#423]
Changing the `FILE_UPLOAD_SIZE_LIMIT` while bookstack does not error out, php.ini dictates the max file is 10M hardcoded.

Alternatives:

Display a log message when `FILE_UPLOAD_SIZE_LIMIT` is changed informing user that has to bind mount a modified php.ini file

Thanks

**Comment by rjhenry** [comment]
Take a look at the linked PR. I'll happily review a PR to make changes to `php.ini` if you bring one forward.
