### ISSUE TITLE
Weird fresh install bug

### ISSUE THREAD

**Issue by joaomelorodrigues** [SolidNerd/docker-bookstack#425]
I installed bookstack with this docker compose:
`version: '3'
services:
  bookstack:
    image: solidnerd/bookstack:23.6.2
    network_mode: bridge
    external_links:
      - cyango-mysql-database:cyango-mysql-database
    environment:
      - DB_HOST=db:3306
      - DB_DATABASE=sads
      - DB_USERNAME=root
      - DB_PASSWORD=pass
      - APP_URL=https://example.com
      - APP_KEY=base64:abaJKlmnOsdsdpasdasd456789ABcDE=
    volumes:
      - /uploads:/var/www/bookstack/public/uploads
      - /storage-uploads:/var/www/bookstack/storage/uploads
    ports:
      - '433416:8080'`
      
      
      And I'm having this on the front page:
      
      
<img width="1728" alt="image" src="https://github.com/solidnerd/docker-bookstack/assets/30806279/4884c487-735b-49bb-910d-c7e1b6ebf350">

Any clue?

**Comment by HJF9w** [comment]
I don't think the APP_KEY variable can be in base64, try with just ``SomeRandomStringWith32Characters``

**Comment by joaomelorodrigues** [comment]
> I don't think the APP_KEY variable can be in base64, try with just `SomeRandomStringWith32Characters`

Yup that was it. Many thanks!
