### ISSUE TITLE
Cannot upload image

### ISSUE THREAD

**Issue by joaomelorodrigues** [SolidNerd/docker-bookstack#426]
I'm trying to upload an image and i get this error

<img width="893" alt="image" src="https://github.com/solidnerd/docker-bookstack/assets/30806279/0d948fdb-f4c3-44b8-8aa2-8b4b3df5b639">

I checked and I have permissions on my volume bind folder uploads and storage-uploads. What could it be?

**Comment by HJF9w** [comment]
Just to verify, the `www-data` user in the container has permissions to write to (in the container) `/var/www/bookstack/public/uploads`? And what `does docker logs docker-bookstack_bookstack_1` say?

**Comment by joaomelorodrigues** [comment]
<img width="694" alt="image" src="https://github.com/solidnerd/docker-bookstack/assets/30806279/043c946c-c69c-47eb-a549-6e6a5a1cca16">

**Comment by HJF9w** [comment]
On the host run `sudo chown -R 33:33 /bind/mount/directory` on the directory that you have bind mounted to `/var/www/bookstack/public/uploads` in the container.

**Comment by joaomelorodrigues** [comment]
It works. Maybe this should be documented. Many thanks.
