### ISSUE TITLE
Too many docker volumes?

### ISSUE THREAD

**Issue by amchelmer** [solidnerd/docker-bookstack#44]
Running `docker-compose up` starts a total of 5 docker volumes, where two are unnamed. It seems they are used for uploads and storage-uploads, whilst `dockerbookstack_storage-uploads` and `dockerbookstack_uploads` remain empty when uploading images in Bookstack.

```
git clone https://github.com/solidnerd/docker-bookstack.git
cd docker-bookstack/
docker-compose up -d
docker volume ls
```
returns
```
DRIVER              VOLUME NAME
local               a6b65c0d08570639759ee0b4ed4dec7356dd41391de7f234e436b9f25e808f52
local               de5deb5b13d07c70f23a52a20737f806950b10c4c33ada5e533e053a4c26da33
local               dockerbookstack_mysql-data
local               dockerbookstack_storage-uploads
local               dockerbookstack_uploads
```

**Comment by vladime** [comment]
I would also like this bug to be fixed.

**Comment by vladime** [comment]
@amchelmer Alex, I have managed get rid of one unnamed volume. In `docker-compose.yml` file you need to change following rows:
`volumes:
    - uploads:/var/www/BookStack/public/uploads
    - storage-uploads:/var/www/BookStack/storage/uploads
`
to
`
volumes:
    - uploads:/var/www/bookstack/public/uploads
    - storage-uploads:/var/www/bookstack/storage/uploads
`

**Comment by amchelmer** [comment]
Good call @vladime. Managed to find the other typo as well. Have submitted a PR.

**Comment by solidnerd** [comment]
Hey, 

it will be available in the next release. (0.17.3)
