### ISSUE TITLE
Missing dependency for bookstack-system-cli

### ISSUE THREAD

**Issue by richie-tt** [SolidNerd/docker-bookstack#441]
Hello,

I wanted to create a full backup of my BookStack using a dedicated  `bookstack-system-cli` application, but there is missing installation of `mysqldump`.

```bash
www-data@bookstack-c884f59d5-8ktj9:~/bookstack$ ./bookstack-system-cli backup 
WARNING: This CLI is in early alpha testing.
There's a high chance of running into bugs, and the CLI API is subject to change.

Checking system requirements...

Warning: ZipArchive::addFile(): No such file or directory in phar:///var/www/bookstack/bookstack-system-cli/src/Commands/BackupCommand.php on line 55
Dumping the database via mysqldump...

An error occurred when attempting to run a command:

Could not locate "mysqldump" program.
```

Can you please add `mysqldump` as part of the docker image?

Environment:

- Kubernetes: 1.25
- Bookstack:  [23.8.3](https://hub.docker.com/layers/solidnerd/bookstack/23.8.3/images/sha256-1a0d4558974446e872cd6b9f5a33de63fe8d2587bdec74df75f806466e4a3749?context=explore)

**Comment by rjhenry** [comment]
Sounds sensible enough to me, feel free to open a PR and I'll review. That said, you should probably know that the CLI won't back up your environment if you're using Kubernetes env vars (as you should be).

You might find it easier to create Kubernetes cron jobs to back up database (via a dump) and your media volume (or, even easier, use S3 or equivalent for media storage).
