### ISSUE TITLE
Container starts with prompt 'Do you really wish to run this command?'

### ISSUE THREAD

**Issue by dionysiusmarquis** [solidnerd/docker-bookstack#45]
Hey,

everytime I start the v0.17.0 container it will stop with a promt. I have to call `exec apache2-foreground > /dev/null 2>&1 &` inside the container to get it running.

```
> php artisan view:clear
stdout
11:00:17
Compiled views cleared!
stdout
11:00:17
[33m**************************************[39m
stdout
11:00:17
[33m*     Application In Production!     *[39m
stdout
11:00:17
[33m**************************************[39m
stdout
11:00:17

stdout
11:00:17
 [32mDo you really wish to run this command? (yes/no)[39m [[33mno[39m]:
```

**Comment by nerdalertdk** [comment]
I also have this error

**Comment by adamgoose** [comment]
Setting `APP_ENV=local`, while not advised for production, will solve this issue. Ultimately, the `--force` flag needs to be added to the migrate command in the container.

**Comment by windhamwong** [comment]
Not sure why this is still open yet, but I would like to add a comment.
If you do `docker run` with the `-it`, it will cause the STDIN and TTY opened and forcing artisan prompting for confirmation and stopping from turning on apache2.

**Comment by Rai-Rai** [comment]
Same for me with version 0.20.0 running on SynologyNas.
Using `APP_ENV=local` crashed the container

**Comment by docfactory37** [comment]
This is is still happening i have  setup this container over the weekend and i'm getting this issue.

see issue Every Startup ask to migrate #1710

**Comment by RaEyE** [comment]
@docfactory37, I second this issue.

I'm currently running solidnerd/docker-bookstack on a Synology NAS and am having the exact same issue (See: https://github.com/BookStackApp/BookStack/issues/1710#issue-506115731).

**Comment by frank505** [comment]
just had this issue right now on github actions cd

**Comment by ghost** [comment]
I have the same problem, has anyone found a solution ?
