### ISSUE TITLE
AzureAD integration

### ISSUE THREAD

**Issue by harding13** [SolidNerd/docker-bookstack#469]
Hi to all,

I would to know what's the best way to integrate third party auth. I would to do this with AzureAD.
This is the link https://www.bookstackapp.com/docs/admin/third-party-auth/#azuread-microsoft

Have I to put the variables in the docker-compose (and re-deploy the container)?

thanks

**Comment by rjhenry** [comment]
Yup, make sure the AAD integration variables are set in the container's environment then re-up the container.
