### ISSUE TITLE
distinguishing features of this image?

### ISSUE THREAD

**Issue by maphew** [SolidNerd/docker-bookstack#470]
What are the distinguishing features of the solidnerd bookstack docker image?

It's approaching 3x the size of linuxserver/bookstack, so I'm wondering: what does the extra heft provide?
Thanks!

**Comment by ssddanbrown** [comment]
@maphew This image is Debian based which can be nice to have compared to the alpine/libmusl base of the linuxserver image (which is what helps make the linuxserver image so small), as you can have odd specific issues pop up in that environment while a debian base can be more familiar to many. This image also includes WKHTMLtoPDF which the linuxserver no longer does.

Ultimately, they are two different images from two different great teams, and it's great both are available to provide options.
