### ISSUE TITLE
Latest Image (24.2.3) Contains Code for 23.2.3

### ISSUE THREAD

**Issue by EgonJGF** [SolidNerd/docker-bookstack#479]
Confirmed in the `/bookstack/version` file.  Also, none of the enhancements for 24.x show up in the installed version.

**Comment by ssddanbrown** [comment]
Can confirm this looking at the diff between tags: https://github.com/solidnerd/docker-bookstack/compare/24.2.2...24.2.3

Also, master seems to be a few steps behind the latest tag release, but not sure if that's actually an issue or not.

**Comment by andremohr** [comment]
Thanks for your work @rjhenry. Unfortunately the [Dockerfile](https://github.com/solidnerd/docker-bookstack/blob/master/Dockerfile) seems to still contain the reference to version 23.02.3 and for me the image from Docker Hub with tag `24.2.3-1` also did.
