### ISSUE TITLE
docker volum

### ISSUE THREAD

**Issue by CordlessWool** [solidnerd/docker-bookstack#61]
I want to ask, why you only share public volume? I want to set a volume to my host system and change the .env, but if I set it with volume option of docker, it empty the bookstack directory. Will it be possible to mount the complete docker folder to host system? 

thank you for the docker container, its a nice work.

**Comment by joshuaavalon** [comment]
You can mount it yourself. 

1. Bash in the image to copy `/var/www/bookstack/.env`.
2. Paste the content to a `.env` (e.g. `/mnt/usr/docker/bookstack/.env`)
3. Add this to your docker create or docker run: 
```
-v /mnt/usr/docker/bookstack/.env:/var/www/bookstack/.env
```

The path above should be correct but I cannot reach my docker config now. I have done something like this.
