### ISSUE TITLE
Suggestion: Change default email to match bookstacks demo

### ISSUE THREAD

**Issue by RayBB** [solidnerd/docker-bookstack#66]
Right now the demo on the official bookstacks email is admin@example.com and the default on this is admin@admin.com.
I it would help avoid some confusion. If you're okay with it I could try to make a PR.

**Comment by ssddanbrown** [comment]
This is not an issue with this docker setup but is part of bookstack itself. Would be better suited to bookstackapp/bookstack.

**Comment by RayBB** [comment]
I opened a ticket on the other repo.
https://github.com/BookStackApp/BookStack/issues/602
