### ISSUE TITLE
Container doesn't write uploads to mapped storage volume

### ISSUE THREAD

**Issue by darkmoon221** [solidnerd/docker-bookstack#80]
First of all thanks for creating this container.

I started using this container some days ago. Today I had to restart my docker infrastructure and had to realize, that all my uploaded documents were gone. I inspected my host volumes and saw, that the mapped `storage` folder was empty. The `uploads` folder on the other side was ok.

My setup is as follows:

* OS: Windows 10, Docker: 18.03.0, Compose: 1.20.1
* I took the declared services from the project's `docker-compse.yml (v2)` and integrated them in my docker-compose (v3) file. 
* Instead of mounting the declared bookstack volumes to a docker volume I defined two volumes on the host.

```
  volumes:
    - C:/Users/someuser/docker-data/bookstack/uploads:/var/www/bookstack/public/uploads
    - C:/Users/someuser/docker-data/bookstack/storage:/var/www/bookstack/public/storage
```

As a first attempt, I tried to mount the `storage` folder to a docker volume, but had the same problem again.

I don't know what I am doing wrong. Maybe someone had the same problem before and found a solution or workaround.

Thanks in advance

**Comment by ssddanbrown** [comment]
Looks like the changes in ef1c962c6841cf261218b702f0cb2dfbe9b15e0f, #44 & #49 are the issue. 

The volume should be `- storage-uploads:/var/www/bookstack/storage/uploads`

**Comment by darkmoon221** [comment]
@ssddanbrown,

I was blind and didn't see that the storage folder is not inside the public folder as declared by the Dockerfile.

My issue is resolved now.

Many thanks for the fast response ;)
