### ISSUE TITLE
lose image

### ISSUE THREAD

**Issue by nickzengxl** [solidnerd/docker-bookstack#83]
I hit two issues when use image，
1. some images disapper with no reason. I don't remove them manually.
2. when I upload new image, it's no the one I upload, but the one already in image list.

Could you help to give some advice.

**Comment by nickzengxl** [comment]
Could you please give me a safe way to add image in page?

**Comment by tylwright** [comment]
Hi @NickZengXL,

Does this happen with BookStack when _not_ using this container?  This sounds like it is or was a bug with BookStack itself and not this container.  In addition, I am unable to repro.

If you're all set, let's go ahead and close this ticket.

Thanks!

**Comment by polarathene** [comment]
@NickZengXL provide the docker/docker-compose setup for others to reproduce is this is still important to you.
