### ISSUE TITLE
High CPU utilization

### ISSUE THREAD

**Issue by Rathorian** [solidnerd/docker-bookstack#89]
Hello,

I've been using your BookStack docker image recently, but I noticed a little annoying problem that I can not solve.

I have 10 Docker containers that run (with the included one) but when I look at using my CPU with https://quay.io/repository/vektorlab/ctop?tab=info, my Bookstack container and the only one that has the CPU percentage really random.
Every 2 seconds, I have CPU percentage changes but very high up to sometimes 107%

People would have the same concern as me?

**Comment by brianofrokk3r** [comment]
Hey @Rathorian I had this same issue, currently debugging, did you ever resolve this?

- I've tried adding database caching as per: https://www.bookstackapp.com/docs/admin/cache-session-config/
- I've tried deploying `0.26.2`

All seem to respond with the same random high CPU, and platform becomes inoperable.

**Comment by brianofrokk3r** [comment]
Quick update:

```
php artisan route:cache
```

I ran right this right in the pod and the performance increased dramatically and CPU utilization decreased.

**Comment by polarathene** [comment]
@brianofrokk3r I'm not a PHP developer, is that safe to use long-term in production?

> In other words, our application no longer has to parse and convert entries from the routes files into `Illuminate/Routing/Route` objects in a `Illuminate/Routing/RouteCollection`. The application also does not call `refreshNameLookups` or `refreshActionLookups`. *Be sure to always regenerate your route cache if you add/modify routes or add service providers that will add/modify your routes.* - [Source](https://www.codementor.io/steven134/laravel-route-caching-for-improved-performance-kemlel9m4)

Is it possible for BookStack to add/modify routes while it's being used(adding new content for example), or are these routes being referred to only concerns with the PHP codebase?

Thanks for sharing the advice. Where abouts should that be run/placed? Should @solidnerd add it to the Dockerfile or entrypoint.sh?
