### ISSUE TITLE
Can't connect with non-default mysql port

### ISSUE THREAD

**Issue by bobnvic** [solidnerd/docker-bookstack#90]
If I change the mysql port I get wait-for-db in the logs, then an exit with code 124. I've tried this on two different systems with the same results. changing the port to default 3306 results in everything working.

docker-compose.yml file with non-default port (doesn't connect to mysql)
version: '2'
services:
  mysql:
    image: mysql:5.7.21
    ports:
    - 3406:3306
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=secret
    volumes:
    - /mnt/data1/storage/docker/bookstack/mysql-data:/var/lib/mysql

  bookstack:
    image: solidnerd/bookstack:0.22.0
    depends_on:
    - mysql
    environment:
    - DB_HOST=mysql:3406
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=secret
    volumes:
    - /mnt/data1/storage/docker/bookstack/uploads:/var/www/bookstack/public/uploads
    - /mnt/data1/storage/docker/bookstack/storage:/var/www/bookstack/public/storage
    ports:
    - "8080:80"

simply changing the 3406 to 3306 in both section allows bookstack to connect to mysql. I can't leave it that way since I have another mysql instance normally running on port 3306.

Any help is greatly appreciated.

Bob

**Comment by bobnvic** [comment]
The solution is that you shouldn't change the mysql port in the bookstack section from the default of 3306. The port mapping only pertains to the host and does not affect the container to container networking, so the default port should always be used from the perspective of the bookstack app. A comment on this line of the docker-compose.yml file to keep the port at 3306 might be helpful for people like myself who simply assumed they should be the same. This ticket can be closed.

**Comment by BugSimon** [comment]
Might be caused by the hard coded port 3306 in docker-entrypoint.sh:8
