### ISSUE TITLE
Clarification About Purpose?

### ISSUE THREAD

**Issue by techdev5521** [solidnerd/docker-bookstack#92]
https://github.com/solidnerd/docker-bookstack/blob/6d1d9c3f26bc9c1f6b56536a43cea2628168e4e4/docker-entrypoint.sh#L91-L95

It seems to me that the while loop's condition on line 92 will never evaluate true, though I could be wrong. Could you please clarify what this does/why it is there?

Thanks.

**Comment by xblitz** [comment]
essentially it waits for the DB to be ready (listening on its defined port) before continuing
